import 'package:feature_split/feature_split.dart';

import 'l10n/app_localizations.dart';

/// Maps generated ARB strings to feature_split label bundles.
class SplitLabels {
  SplitLabels._();

  static MainShellLabels shell(AppLocalizations l10n) => MainShellLabels(
        trips: l10n.navTrips,
        activity: l10n.navActivity,
        expenses: l10n.navExpenses,
        profile: l10n.navProfile,
        add: l10n.navAdd,
        createTrip: l10n.tripsCreateTripTooltip,
        addExpense: l10n.addExpenseTitle,
        addExpensePickerTitle: l10n.expensesPickerTitle,
        addExpenseLastUsed: l10n.expensesPickerLastUsed,
      );

  static TripsListScreenLabels trips(AppLocalizations l10n) =>
      TripsListScreenLabels(
        title: l10n.tripsTitle,
        emptyTitle: l10n.tripsEmptyTitle,
        emptySubtitle: l10n.tripsEmptySubtitle,
        emptyUpcomingTitle: l10n.tripsEmptyUpcomingTitle,
        emptyPastTitle: l10n.tripsEmptyPastTitle,
        syncPendingLabel: l10n.tripsSyncPending,
        syncSubtitle: l10n.tripsSyncSubtitle,
        filterAll: l10n.tripsFilterAll,
        filterUpcoming: l10n.tripsFilterUpcoming,
        filterPast: l10n.tripsFilterPast,
        filterDrafts: l10n.tripsFilterDrafts,
        loadError: l10n.tripsLoadError,
        syncError: l10n.tripsSyncError,
        sectionUpcoming: l10n.tripsSectionUpcoming,
        sectionPast: l10n.tripsSectionPast,
        participants: l10n.tripsParticipants,
        notificationsTooltip: l10n.tripsNotificationsTooltip,
        notificationsUnreadBadge: l10n.notificationsUnreadBadge,
        createTripTooltip: l10n.tripsCreateTripTooltip,
        weather: weather(l10n),
      );

  static WeatherBadgeLabels weather(AppLocalizations l10n) =>
      WeatherBadgeLabels(
        temp: l10n.weatherPreviewTemp,
        semanticSunny: l10n.weatherPreviewSunny,
        semanticCloudy: l10n.weatherPreviewCloudy,
        semanticRain: l10n.weatherPreviewRain,
        semanticThunderstorm: l10n.weatherPreviewThunderstorm,
        semanticSnow: l10n.weatherPreviewSnow,
        semanticFog: l10n.weatherPreviewFog,
        semanticUnknown: l10n.weatherPreviewUnknown,
      );

  static NotificationLabels notifications(AppLocalizations l10n) =>
      NotificationLabels(
        inboxTitle: l10n.notificationsInboxTitle,
        emptyTitle: l10n.notificationsEmptyTitle,
        emptySubtitle: l10n.notificationsEmptySubtitle,
        markAllRead: l10n.notificationsMarkAllRead,
        unreadBadge: (count) => l10n.notificationsUnreadBadge(count),
        typeCloseNotice: l10n.notificationTypeCloseNotice,
        typeCloseReminder: l10n.notificationTypeCloseReminder,
        typeDeemedClosed: l10n.notificationTypeDeemedClosed,
        typeSettleNudge: l10n.notificationTypeSettleNudge,
        typeWrappedTrip: l10n.notificationTypeWrappedTrip,
        typePremiumGate: l10n.notificationTypePremiumGate,
        typeGeneric: l10n.notificationTypeGeneric,
      );

  static ActivityScreenLabels activity(AppLocalizations l10n) =>
      ActivityScreenLabels(
        title: l10n.activityTitle,
        emptyTitle: l10n.activityEmptyTitle,
        emptySubtitle: l10n.activityEmptySubtitle,
        loadError: l10n.activityLoadError,
        eventCreatedSubtitle: l10n.activityEventCreatedSubtitle,
        eventRsvpSubtitle: (status) => l10n.activityEventRsvpSubtitle(status),
        rsvpGoing: l10n.eventRsvpGoing,
        rsvpMaybe: l10n.eventRsvpMaybe,
        rsvpDeclined: l10n.eventRsvpDeclined,
      );

  static ExpensesListScreenLabels expenses(AppLocalizations l10n) =>
      ExpensesListScreenLabels(
        title: l10n.expensesTitle,
        emptyTitle: l10n.expensesEmptyTitle,
        emptySubtitle: l10n.expensesEmptySubtitle,
        loadError: l10n.expensesLoadError,
        balanceAllSettled: l10n.expensesBalanceAllSettled,
        balanceYouOwe: l10n.expensesBalanceYouOwe,
        balanceYouAreOwed: l10n.expensesBalanceYouAreOwed,
        balanceAcrossTrips: l10n.expensesBalanceAcrossTrips,
        periodThisMonth: l10n.expensesPeriodThisMonth,
        periodThisYear: l10n.expensesPeriodThisYear,
        earlierSection: l10n.expensesEarlierSection,
        totalSpent: l10n.expensesTotalSpent,
        myShare: l10n.expensesMyShare,
        settlementUnsettled: l10n.expensesSettlementUnsettled,
        settlementSettled: l10n.expensesSettlementSettled,
        settlementAllSettled: l10n.expensesSettlementAllSettled,
        unresolvedBadge: l10n.expensesUnresolvedBadge,
        pickerTitle: l10n.expensesPickerTitle,
        pickerLastUsed: l10n.expensesPickerLastUsed,
        addExpenseTooltip: l10n.addExpenseTitle,
      );

  static PlanTabLabels plan(AppLocalizations l10n) => PlanTabLabels(
        tabTitle: l10n.planTabTitle,
        emptyTitle: l10n.planEmptyTitle,
        emptySubtitle: l10n.planEmptySubtitle,
        undatedSection: l10n.planUndatedSection,
        checklistsSection: l10n.planChecklistsSection,
        addPlanItem: l10n.planAddItem,
        mainTripSection: l10n.planMainTripSection,
        addSubtrip: l10n.planAddSubtrip,
        subtripNameLabel: l10n.planSubtripNameLabel,
        subtripMembersLabel: l10n.planSubtripMembersLabel,
        subtripNameRequired: l10n.planSubtripNameRequired,
        subtripMembersRequired: l10n.planSubtripMembersRequired,
        subtripCreateFailed: l10n.planSubtripCreateFailed,
        addListItemHint: l10n.planAddListItemHint,
        defaultListName: l10n.planDefaultListName,
        deleteItem: l10n.planDeleteItem,
        editItem: l10n.planEditItem,
        kindLodging: l10n.planKindLodging,
        kindFlight: l10n.planKindFlight,
        kindTrain: l10n.planKindTrain,
        kindActivity: l10n.planKindActivity,
        kindVisit: l10n.planKindVisit,
        kindTransfer: l10n.planKindTransfer,
        kindOther: l10n.planKindOther,
        sheetTitleAdd: l10n.planSheetTitleAdd,
        sheetTitleEdit: l10n.planSheetTitleEdit,
        fieldTitle: l10n.planFieldTitle,
        fieldKind: l10n.planFieldKind,
        fieldNotes: l10n.planFieldNotes,
        fieldStart: l10n.planFieldStart,
        fieldEnd: l10n.planFieldEnd,
        visitSectionTitle: l10n.planVisitSectionTitle,
        visitFromTripPlaces: l10n.planVisitFromTripPlaces,
        visitPlaceLabel: l10n.planVisitPlaceLabel,
        visitPlaceHelper: l10n.planVisitPlaceHelper,
        visitAddressLabel: l10n.planVisitAddressLabel,
        visitAddressHelper: l10n.planVisitAddressHelper,
        visitFindCoordinates: l10n.planVisitFindCoordinates,
        visitPlaceRequired: l10n.planVisitPlaceRequired,
        visitAddressRequiredForGeocode: l10n.planVisitAddressRequiredForGeocode,
        visitCoordinatesSaved: l10n.planVisitCoordinatesSaved,
        visitCoordinatesNotFound: l10n.planVisitCoordinatesNotFound,
        visitDiscoverNearby: l10n.planVisitDiscoverNearby,
        visitDiscoverHelper: l10n.planVisitDiscoverHelper,
        visitDiscoverNeedsPlace: l10n.planVisitDiscoverNeedsPlace,
        visitDiscoverResolving: l10n.planVisitDiscoverResolving,
        visitDiscoverNeedsCoordinates: l10n.planVisitDiscoverNeedsCoordinates,
        visitDiscoverEmpty: l10n.planVisitDiscoverEmpty,
        visitDiscoverGated: l10n.planVisitDiscoverGated,
        visitDiscoverLoadError: l10n.planVisitDiscoverLoadError,
        ctaTapType: l10n.planCtaTapType,
        ctaTapPlace: l10n.planCtaTapPlace,
        transferSectionTitle: l10n.planTransferSectionTitle,
        transferSubtypeLabel: l10n.planTransferSubtypeLabel,
        transferOriginLabel: l10n.planTransferOriginLabel,
        transferDestinationLabel: l10n.planTransferDestinationLabel,
        transferProviderLabel: l10n.planTransferProviderLabel,
        transferReferenceLabel: l10n.planTransferReferenceLabel,
        transferSubtypeCarRental: l10n.planTransferSubtypeCarRental,
        transferSubtypeTrain: l10n.planTransferSubtypeTrain,
        transferSubtypeTransit: l10n.planTransferSubtypeTransit,
        transferSubtypeDrive: l10n.planTransferSubtypeDrive,
        transferSubtypeFlight: l10n.planTransferSubtypeFlight,
        save: l10n.planSave,
        loadError: l10n.planLoadError,
        checklistsLoadError: l10n.planChecklistsLoadError,
        rsvpGoing: l10n.eventRsvpGoing,
        rsvpMaybe: l10n.eventRsvpMaybe,
        rsvpDeclined: l10n.eventRsvpDeclined,
        rsvpSummary: (going, maybe, declined) =>
            l10n.eventRsvpSummary(going, maybe, declined),
        eventRsvpHint: l10n.planEventRsvpHint,
        eventRsvpSection: l10n.planEventRsvpSection,
        eventRsvpUpdateFailed: l10n.eventRsvpUpdateFailed,
        datePickerCancel: l10n.datePickerCancel,
        datePickerSkip: l10n.datePickerSkip,
        datePickerSelect: l10n.datePickerSelect,
        addChecklistItem: l10n.planAddChecklistItem,
        deleteConfirmTitle: l10n.planDeleteConfirmTitle,
        endBeforeStart: l10n.planEndBeforeStart,
        cancelLabel: l10n.datePickerCancel,
      );

  static ExpenseGovernanceLabels governance(AppLocalizations l10n) =>
      ExpenseGovernanceLabels(
        includedDisputedBy: l10n.expenseIncludedDisputedBy,
        includedPendingFrom: l10n.expenseIncludedPendingFrom,
        someoneFallback: l10n.expenseSomeoneFallback,
        proposalRowPrefix: l10n.expenseProposalRowPrefix,
        proposalNotInBalances: l10n.expenseProposalNotInBalances,
        shareAccepted: l10n.expenseShareAccepted,
        yourShare: l10n.expenseYourShare,
        dispute: l10n.expenseDispute,
        accept: l10n.expenseAccept,
        commitToBalances: l10n.expenseCommitToBalances,
        voidProposal: l10n.expenseVoidProposal,
        disputeReasonTitle: l10n.expenseDisputeReasonTitle,
        disputeReasonHint: l10n.expenseDisputeReasonHint,
        cancel: l10n.expenseGovernanceCancel,
        submit: l10n.expenseGovernanceSubmit,
        proposeCostAction: l10n.expenseProposeCostAction,
        addExpenseTitle: l10n.expenseAddTitle,
        proposeCostTitle: l10n.expenseProposeCostTitle,
        saveExpense: l10n.expenseSaveExpense,
        saveProposal: l10n.expenseSaveProposal,
        tripBalancesIn: l10n.expenseTripBalancesIn,
        splitEqual: l10n.expenseSplitEqual,
        splitSolo: l10n.expenseSplitSolo,
        convertedAmountLabel: l10n.expenseConvertedAmountLabel,
        fxConversionLocked: l10n.expenseFxConversionLocked,
        saveConversion: l10n.expenseSaveConversion,
        fxSourceReceipt: l10n.expenseFxSourceReceipt,
      );

  static TripBudgetLabels budget(AppLocalizations l10n) => TripBudgetLabels(
        settingsTitle: l10n.tripSettingsTitle,
        budgetSectionTitle: l10n.tripBudgetSectionTitle,
        budgetModeNone: l10n.tripBudgetModeNone,
        budgetModeInformational: l10n.tripBudgetModeInformational,
        budgetModeFormal: l10n.tripBudgetModeFormal,
        budgetAmountLabel: l10n.tripBudgetAmountLabel,
        saveBudget: l10n.tripBudgetSave,
        burnDownRemaining: (remainingCents, currency) =>
            l10n.tripBudgetRemaining(
          formatMoneyFromCents(remainingCents, currency),
          currency,
        ),
        burnDownOver: (currency) => l10n.tripBudgetOver(currency),
        fxSectionTitle: l10n.tripFxSectionTitle,
        fxAddCurrency: l10n.tripFxAddCurrency,
        fxRefresh: l10n.tripFxRefresh,
        fxCapturedAt: l10n.tripFxCapturedAt,
        fxSource: l10n.tripFxSource,
        fxRateReadOnly: l10n.tripFxRateReadOnly,
        overBudgetCommitTitle: l10n.tripOverBudgetCommitTitle,
        overBudgetCommitBody: l10n.tripOverBudgetCommitBody,
        overBudgetConfirmHint: l10n.tripOverBudgetConfirmHint,
        overBudgetConfirmPhrase: l10n.tripOverBudgetConfirmPhrase,
        confirm: l10n.tripBudgetConfirm,
        cancel: l10n.tripBudgetCancel,
        currencyMissingAdmin: l10n.tripCurrencyMissingAdmin,
        datesSectionTitle: l10n.tripDatesSectionTitle,
        startDateLabel: l10n.createTripStartDate,
        endDateLabel: l10n.createTripEndDate,
        saveDates: l10n.tripDatesSave,
        startDateLockedHint: l10n.tripDatesStartLocked,
        endBeforeStart: l10n.createTripEndBeforeStart,
        datePickerCancel: l10n.datePickerCancel,
        datePickerSkip: l10n.datePickerSkip,
        datePickerSelect: l10n.datePickerSelect,
        retentionSectionTitle: l10n.tripRetentionSectionTitle,
        subtripsSectionTitle: l10n.tripSubtripsSectionTitle,
        subtripsToggleLabel: l10n.tripSubtripsToggleLabel,
        subtripsToggleBody: l10n.tripSubtripsToggleBody,
        subtripsSaveError: l10n.tripSubtripsSaveError,
        offloadMedia: l10n.tripOffloadMedia,
        offloadMediaBody: l10n.tripOffloadMediaBody,
        offloadMediaConfirmTitle: l10n.tripOffloadMediaConfirmTitle,
        offloadMediaConfirmBody: l10n.tripOffloadMediaConfirmBody,
        offloadMediaSuccess: l10n.tripOffloadMediaSuccess,
        offloadMediaNothing: l10n.tripOffloadMediaNothing,
      );

  static TripLifecycleLabels lifecycle(AppLocalizations l10n) =>
      TripLifecycleLabels(
        markDone: l10n.tripLifecycleMarkDone,
        requestClose: l10n.tripLifecycleRequestClose,
        cancelTrip: l10n.tripLifecycleCancelTrip,
        acceptClose: l10n.tripLifecycleAcceptClose,
        objectToClose: l10n.tripLifecycleObject,
        withdrawObjection: l10n.tripLifecycleWithdrawObjection,
        closeAnyway: l10n.tripLifecycleCloseAnyway,
        cancelledBanner: l10n.tripLifecycleCancelledBanner,
        closedBanner: l10n.tripLifecycleClosedBanner,
        closingBannerGeneric: l10n.tripLifecycleClosingGeneric,
        closingBannerDays: l10n.tripLifecycleClosingCountdown,
        objectionNotice: l10n.tripLifecycleObjectionNotice,
        markDoneTitle: l10n.tripLifecycleMarkDoneTitle,
        markDoneBody: l10n.tripLifecycleMarkDoneBody,
        markDoneConfirm: l10n.tripLifecycleMarkDoneConfirm,
        notYet: l10n.tripLifecycleNotYet,
        cancelTripTitle: l10n.tripLifecycleCancelTitle,
        cancelTripBody: l10n.tripLifecycleCancelBody,
        keepTrip: l10n.tripLifecycleKeepTrip,
        requestCloseTitle: l10n.tripLifecycleRequestCloseTitle,
        requestCloseBody: l10n.tripLifecycleRequestCloseBody,
        requestCloseConfirm: l10n.tripLifecycleRequestCloseConfirm,
        tripActions: l10n.tripLifecycleTripActions,
        closeAnywayTitle: l10n.tripLifecycleCloseAnywayTitle,
        closeAnywayBody: l10n.tripLifecycleCloseAnywayBody,
        closeAnywayHint: l10n.tripLifecycleCloseAnywayHint,
        closeAnywayPhrase: l10n.tripLifecycleCloseAnywayPhrase,
        closeTrip: l10n.tripLifecycleCloseTrip,
        back: l10n.tripLifecycleBack,
        objectTitle: l10n.tripLifecycleObjectTitle,
        objectReasonLabel: l10n.tripLifecycleObjectReasonLabel,
        objectReasonHint: l10n.tripLifecycleObjectReasonHint,
        submitObjection: l10n.tripLifecycleSubmitObjection,
        softClosedBanner: l10n.tripLifecycleSoftClosedBanner,
        reliveTrip: l10n.tripLifecycleReliveTrip,
        reopenTrip: l10n.tripLifecycleReopenTrip,
      );

  static InviteLabels invite(AppLocalizations l10n) => InviteLabels(
        showQr: l10n.inviteShowQr,
        scanQr: l10n.inviteScanQr,
        qrCaption: l10n.inviteQrCaption,
        notVamoInvite: l10n.inviteNotVamoQr,
        cameraDenied: l10n.inviteCameraDenied,
        pasteLink: l10n.invitePasteLink,
        pasteHint: l10n.invitePasteHint,
        pasteJoin: l10n.invitePasteJoin,
        scannerTitle: l10n.inviteScannerTitle,
        inviteVamigos: l10n.inviteVamigos,
        inviteAction: l10n.inviteAction,
        shareJoinLink: l10n.inviteShareJoinLink,
        inviteFromContacts: l10n.inviteFromContacts,
        contactMethodTextMessage: l10n.inviteContactMethodTextMessage,
        contactMethodEmail: l10n.inviteContactMethodEmail,
        contactMethodShareLink: l10n.inviteContactMethodShareLink,
        contactInviteSubject: l10n.inviteContactSubject,
        contactInviteBody: l10n.inviteContactBody,
        membersVamigosTitle: l10n.membersVamigosTitle,
        membersInviteHintSolo: l10n.membersInviteHintSolo,
        membersShareFootnote: l10n.membersShareFootnote,
        membersCountOnTrip: l10n.membersCountOnTrip,
        membersMakeCoAdmin: l10n.membersMakeCoAdmin,
        membersRemoveCoAdmin: l10n.membersRemoveCoAdmin,
      );

  static ProfileScreenLabels profile(AppLocalizations l10n) =>
      ProfileScreenLabels(
        title: l10n.profileTitle,
        aboutSection: l10n.profileAbout,
        versionLabel: l10n.profileVersion,
        licenses: l10n.profileLicenses,
        privacyPolicy: l10n.profilePrivacy,
        tagline: l10n.brandTagline,
        loadError: l10n.profileLoadError,
        profileSection: l10n.profileSection,
        appearanceSection: l10n.profileAppearanceSection,
        appearanceLight: l10n.profileAppearanceLight,
        appearanceDark: l10n.profileAppearanceDark,
        appearanceSystem: l10n.profileAppearanceSystem,
        privacySection: l10n.profilePrivacySection,
        tagCaptureLocation: l10n.profileTagCaptureLocation,
        tagCaptureLocationHelper: l10n.profileTagCaptureLocationHelper,
        displayName: l10n.profileDisplayName,
        displayNameHint: l10n.profileDisplayNameHint,
        displayNameRequired: l10n.profileDisplayNameRequired,
        displayNameReserved: l10n.profileDisplayNameReserved,
        defaultCurrency: l10n.profileDefaultCurrency,
        defaultCurrencyHelper: l10n.profileDefaultCurrencyHelper,
        completionTitle: l10n.profileCompletionTitle,
        completionSubtitle: l10n.profileCompletionSubtitle,
        avatarSection: l10n.profileAvatarSection,
        avatarUseOAuth: l10n.profileAvatarUseOAuth,
        avatarUpload: l10n.profileAvatarUpload,
        avatarUseInitials: l10n.profileAvatarUseInitials,
        avatarUsePhoto: l10n.profileAvatarUsePhoto,
        avatarRemovePhoto: l10n.profileAvatarRemovePhoto,
        avatarRemovePhotoTitle: l10n.profileAvatarRemovePhotoTitle,
        avatarRemovePhotoBody: l10n.profileAvatarRemovePhotoBody,
        avatarRemovePhotoCancel: l10n.profileAvatarRemovePhotoCancel,
        avatarRemovePhotoConfirm: l10n.profileAvatarRemovePhotoConfirm,
        avatarInitialsLabel: l10n.profileAvatarInitialsLabel,
        avatarInitialsHint: l10n.profileAvatarInitialsHint,
        billingSection: l10n.profileBilling,
        plusTitle: l10n.profilePlusTitle,
        plusSubtitle: l10n.profilePlusSubtitle,
        plusSheetDescription: l10n.profilePlusSheetDescription,
        suggestTitle: l10n.profileSuggestTitle,
        suggestSubtitle: l10n.profileSuggestSubtitle,
        devLocaleSection: l10n.settingsDevLocaleSection,
        devLocaleSystem: l10n.settingsDevLocaleSystem,
        devLocaleRtl: l10n.settingsDevLocaleRtl,
        devLocalePseudo: l10n.settingsDevLocalePseudo,
        analyticsSection: l10n.profileAnalytics,
        analyticsHint: l10n.profileAnalyticsHint,
        posthogActive: l10n.profilePosthogActive,
        signOut: l10n.profileSignOut,
        saveChanges: l10n.profileSave,
        profileSaved: l10n.profileSaved,
        pendingMediaTitle: l10n.profilePendingMediaTitle,
        pendingMediaBody: (count) => l10n.profilePendingMediaBody(count),
        pendingMediaStay: l10n.profilePendingMediaStay,
        pendingMediaDiscard: l10n.profilePendingMediaDiscard,
      );

  static TripHomeLabels tripHome(AppLocalizations l10n) => TripHomeLabels(
        tabOverview: l10n.tripHomeTabOverview,
        tabExpenses: l10n.tripHomeTabExpenses,
        tabCapture: l10n.tripHomeTabCapture,
        memoriesTitle: l10n.tripHomeMemories,
        tabBalances: l10n.tripHomeTabBalances,
        tabMembers: l10n.tripHomeTabMembers,
        moreMenu: l10n.tripHomeMoreMenu,
        tripSettings: l10n.tripHomeSettings,
        shareSnapshot: l10n.tripHomeShareSnapshot,
        closeReport: l10n.tripHomeCloseReport,
        addExpense: l10n.tripHomeAddExpense,
        loadError: l10n.tripHomeLoadError,
        notFoundTitle: l10n.tripHomeNotFoundTitle,
        notFoundSubtitle: l10n.tripHomeNotFoundSubtitle,
        totalSpentLabel: l10n.tripHomeTotalSpent,
        perPersonLabel: l10n.tripHomePerPerson,
        recentActivity: l10n.tripHomeRecentActivity,
        noRecentActivity: l10n.tripHomeNoRecentActivity,
        quickExpenses: l10n.tripHomeQuickExpenses,
        quickPlans: l10n.tripHomeQuickPlans,
        quickBalances: l10n.tripHomeQuickBalances,
        quickMembers: l10n.tripHomeQuickMembers,
        quickMemories: l10n.tripHomeQuickMemories,
      );

  static BalancesTabLabels balances(AppLocalizations l10n) => BalancesTabLabels(
        loadError: l10n.balancesLoadError,
        whoOwesWhomTitle: l10n.balancesWhoOwesTitle,
        whoOwesWhomHint: l10n.balancesWhoOwesHint,
        paysLine: l10n.balancesPaysLine,
        waitingForPayer: l10n.balancesWaitingForPayer,
        markAsSettled: l10n.balancesMarkSettled,
        netHeroTitle: l10n.balancesNetHeroTitle,
        netHeroSettled: l10n.balancesNetHeroSettled,
        netHeroYouOwe: l10n.balancesNetHeroYouOwe,
        netHeroYouAreOwed: l10n.balancesNetHeroYouAreOwed,
        settleUp: l10n.balancesSettleUp,
        myActionTitle: l10n.balancesMyActionTitle,
        confirmPaymentsHint: l10n.balancesConfirmHint,
        confirmPaymentFrom: l10n.balancesConfirmFrom,
        confirm: l10n.balancesConfirm,
        reject: l10n.balancesReject,
        awaitingConfirmationTitle: l10n.balancesAwaitingTitle,
        awaitingConfirmationHint: l10n.balancesAwaitingHint,
        youToRecipient: l10n.balancesYouToRecipient,
        markedNotConfirmed: l10n.balancesMarkedNotConfirmed,
        cancelMark: l10n.balancesCancelMark,
        disputedTitle: l10n.balancesDisputedTitle,
        finalTitle: l10n.balancesFinalTitle,
        netBalanceLine: (name, isOwed, amount) => l10n.balancesNetLine(
          name,
          isOwed ? l10n.balancesNetOwed : l10n.balancesNetOwes,
          amount,
        ),
        emptyTitle: l10n.balancesEmptyTitle,
        emptySubtitle: l10n.balancesEmptySubtitle,
        paymentConfirmed: l10n.balancesPaymentConfirmed,
        markedNotReceived: l10n.balancesMarkedNotReceived,
        markCancelled: l10n.balancesMarkCancelled,
        someoneFallback: l10n.expenseSomeoneFallback,
      );

  static CloseReportLabels closeReport(AppLocalizations l10n) =>
      CloseReportLabels(
        title: l10n.closeReportTitle,
        loadError: l10n.closeReportLoadError,
        notAvailable: l10n.closeReportNotAvailable,
        balancesTitle: l10n.closeReportBalancesTitle,
        membersTitle: l10n.closeReportMembersTitle,
        disputedTitle: l10n.closeReportDisputedTitle,
        consentAccepted: l10n.closeReportConsentAccepted,
        consentObjected: l10n.closeReportConsentObjected,
        consentDeemed: l10n.closeReportConsentDeemed,
        consentPending: l10n.closeReportConsentPending,
        consentNotNotified: l10n.closeReportConsentNotNotified,
        balanceLine: (name, isOwed, amount) => l10n.closeReportBalanceLine(
          name,
          isOwed ? l10n.closeReportNetOwed : l10n.closeReportNetOwes,
          amount,
        ),
        noBalances: l10n.closeReportNoBalances,
      );

  static AuthLabels auth(AppLocalizations l10n) => AuthLabels(
        tagline: l10n.brandTagline,
        emailLabel: l10n.authEmailLabel,
        emailHint: l10n.authEmailHint,
        otpLabel: l10n.authOtpLabel,
        codeSent: l10n.authCodeSent,
        continueWithEmail: l10n.authContinueEmail,
        verifyAndContinue: l10n.authVerifyContinue,
        useDifferentEmail: l10n.authDifferentEmail,
        orDivider: l10n.authOrDivider,
        continueWithApple: l10n.authContinueApple,
        continueWithGoogle: l10n.authContinueGoogle,
        resendCode: l10n.authResendCode,
        resendCodeCooldown: l10n.authResendCodeCooldown,
      );

  static CreateTripLabels createTrip(AppLocalizations l10n) => CreateTripLabels(
        title: l10n.createTripTitle,
        headline: l10n.createTripHeadline,
        subtitle: l10n.createTripSubtitle,
        nameLabel: l10n.createTripNameLabel,
        nameHint: l10n.createTripNameHint,
        nameRequired: l10n.createTripNameRequired,
        destinationLabel: l10n.createTripDestinationLabel,
        destinationHint: l10n.createTripDestinationHint,
        currencyLabel: l10n.createTripCurrencyLabel,
        startDate: l10n.createTripStartDate,
        endDate: l10n.createTripEndDate,
        submit: l10n.createTripSubmit,
        endBeforeStart: l10n.createTripEndBeforeStart,
        clearDate: l10n.createTripClearDate,
        datePickerCancel: l10n.datePickerCancel,
        datePickerSkip: l10n.datePickerSkip,
        datePickerSelect: l10n.datePickerSelect,
      );

  static AddExpenseScreenLabels addExpense(AppLocalizations l10n) =>
      AddExpenseScreenLabels(
        title: l10n.addExpenseTitle,
        tripNotFound: l10n.addExpenseTripNotFound,
        scanReceipt: l10n.addExpenseScanReceipt,
        takePhoto: l10n.addExpenseTakePhoto,
        chooseGallery: l10n.addExpenseChooseGallery,
        choosePayer: l10n.addExpenseChoosePayer,
      );
}
