import 'package:feature_split/src/travel/advanced_travel_labels.dart';

/// Shared AdvancedTravelLabels fixture for the travel-feature widget tests.
const advancedTravelTestLabels = AdvancedTravelLabels(
  toggleTitle: 'Multimodal',
  toggleBadge: 'Advanced',
  toggleSubtitle: 'Multi-modal legs',
  legsSectionTitle: 'Travel legs',
  legsInOrder: 'in order',
  addLeg: 'Add leg',
  noLegs: 'No legs yet',
  draftWithAi: 'Draft route with AI',
  draftWithAiBadge: 'Vamo AI',
  draftComingSoon: 'Coming soon',
  planItMyself: "I'll plan it myself",
  aiFootnote: 'AI is optional',
  legEditorTitle: 'Travel leg',
  removeLeg: 'Remove',
  modeSectionTitle: 'Mode',
  windowSectionTitle: 'When you can travel',
  windowAnyTime: 'Any time',
  windowOptionalHint: 'Times optional',
  reachSectionTitle: 'Reach limit',
  reachDistance: 'Distance',
  reachTime: 'Time',
  reachNoLimit: 'No limit',
  reachDistanceCaption: "max you'll cover",
  reachTimeCaption: 'max per day',
  reachHoursUnit: 'h / day',
  unitsFootnote: 'Units follow your profile',
  saveLeg: 'Save leg',
  modeCar: 'Car',
  modeMotorbike: 'Motorbike',
  modeBike: 'Bike',
  modeTrain: 'Train',
  modeFlight: 'Flight',
  modeBus: 'Bus',
  reviewTitle: 'Route draft',
  reviewSubtitle: 'Pick the stops to add.',
  reviewWarningsTitle: 'Heads up',
  reviewQuestionsTitle: 'Open questions',
  reviewAddToPlan: 'Add to plan',
  reviewSkip: 'Not now',
  reviewCommitting: 'Adding…',
  reviewEmpty: 'No stops were drafted.',
  draftGatedMessage: 'Out of free drafts.',
  draftFailedMessage: 'Could not draft.',
);
